### ISSUE TITLE
[ ALL ] Font family, Font weight

### ISSUE THREAD

**Issue by lester-ar-ibinex-tech** [IbinexPH/ibinex-web#2]
Please, check font family and weight of **ALL** pages against the standard.

<h2>Some Expected</h2>

Why Page:
1)
![image](https://user-images.githubusercontent.com/37060596/39228449-ddb795da-4890-11e8-871d-b98260892198.png)
2)
![image](https://user-images.githubusercontent.com/37060596/39230381-e0236a80-4898-11e8-8070-a5056222cdfc.png)
3)
Header section:
![image](https://user-images.githubusercontent.com/37060596/39230489-3e0bf810-4899-11e8-8d27-148c6c12f3e8.png)

<h2>Some Generated</h2>

Why Page:
1)
![image](https://user-images.githubusercontent.com/37060596/39228469-f2879000-4890-11e8-9aab-531bde2bc403.png)
2)
![image](https://user-images.githubusercontent.com/37060596/39230403-f06230e8-4898-11e8-9fff-6834a8e5e9d8.png)
3)
Header section:
![image](https://user-images.githubusercontent.com/37060596/39230720-164eb032-489a-11e8-9ef0-952d675f119b.png)

**Comment by jctiru-ibinex** [comment]
General fonts have been changed.
