### ISSUE TITLE
[ CONTACT ] @992-1030 No Spacing on Title First Fold

### ISSUE THREAD

**Issue by lester-ar-ibinex-tech** [IbinexPH/ibinex-web#27]
Title on First Fold should have  spacing on top of it to make it readable.

Generated @992
![image](https://user-images.githubusercontent.com/37060596/39415466-61b839a0-4c76-11e8-8f0c-14ca57c6a26e.png)

Generated @1030
![image](https://user-images.githubusercontent.com/37060596/39415481-75836bc6-4c76-11e8-94c5-18d37aebb216.png)

**Comment by jctiru-ibinex** [comment]
Same issue with #33.
