### ISSUE TITLE
[PRICING] Title Overflows

### ISSUE THREAD

**Issue by seanibinex** [IbinexPH/ibinex-web#31]
Second Fold Overflow, Expected result should be like second paragraph

![image](https://user-images.githubusercontent.com/37060404/39415692-f0e0e882-4c78-11e8-8b61-2f1c8c674564.png)

![image](https://user-images.githubusercontent.com/37060404/39415696-ff936120-4c78-11e8-9359-258fb572b2ab.png)

**Comment by jctiru-ibinex** [comment]
Copy paste on WYSIWYG adds ```&nbsp;``` (non-breaking space).
![image](https://user-images.githubusercontent.com/37566652/39416197-b0a132a4-4c7d-11e8-9e7b-e0efc6248193.png)
![image](https://user-images.githubusercontent.com/37566652/39416206-c3fec7e4-4c7d-11e8-91fe-f5741ab00aae.png)

Typing by normal means doesn't add ```&nbsp;```
![image](https://user-images.githubusercontent.com/37566652/39416228-f3161b7c-4c7d-11e8-9f34-117a1f126905.png)
![image](https://user-images.githubusercontent.com/37566652/39416236-ffa93630-4c7d-11e8-8af6-5993420b7c6c.png)
