### ISSUE TITLE
[ CONTACT ] Contact Us Hero Section is Not Dynamic on All Devices

### ISSUE THREAD

**Issue by lester-ar-ibinex-tech** [IbinexPH/ibinex-web#32]
**Scenario**:
Contact Us Hero Section contents has twice the original content.

**Expected Behavior:**
Even without Hero Section Title, the spacing above the content should be large enough to push succeeding contents -- so as to make the contents readable by not overlapping with the background image.

**Generated**:
![image](https://user-images.githubusercontent.com/37060596/39415706-1eaa493e-4c79-11e8-84cf-c1e49bccea54.png)

**Comment by jctiru-ibinex** [comment]
Complicated situation. On first hand, the original CSS is based on the design template. By changing the background (dynamic), another problem will arise that needs to be addressed. This needs further discussion.
